//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringKesehatanBank_HaidarAW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DataKesehatan
    {
        public string SandiBank { get; set; }
        public string Periode { get; set; }
        public double KreditKol1 { get; set; }
        public double KreditKol2 { get; set; }
        public double KreditKol3 { get; set; }
        public double KreditKol4 { get; set; }
        public double KreditKol5 { get; set; }
        public double Laba { get; set; }
        public double Modal { get; set; }
        public double TotalAset { get; set; }
        public double ATMR { get; set; }
        public double BebanOperasional { get; set; }
        public double PendapatanOperasional { get; set; }
        public double DanaPihakKe3 { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,0.00}")]
        public Nullable<double> NPL { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,0.00}")]
        public Nullable<double> ROE { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,0.00}")]
        public Nullable<double> ROA { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,0.00}")]
        public Nullable<double> LDR { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,0.00}")]
        public Nullable<double> BOPO { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,0.00}")]
        public Nullable<double> CAR { get; set; }
        public Nullable<int> TotalRedColor { get; set; }
    }
}
